import { describe, expect, it } from 'vitest'
import { computePaths, distance, dot, intersect, mirror, roomSurfaces, solvePath, sub, treatmentSurface } from './acoustics'
import { demo, distanceLabel, ft, inches, makeObject, mountObject, mountTreatmentAtPoint, toFeet, validateDesign } from './model'
import type { RaySettings } from './acoustics'
import type { Design, Vec3 } from './model'
const room = { width: 5, height: 3, length: 6 }
const surfaces = roomSurfaces(room)
const settings: RaySettings = { enabled: true, first: true, second: true, listener: 'listener-a', band: '1000', surfaces: { front: true, rear: true, left: true, right: true, floor: true, ceiling: true }, maxSecond: 40, quality: 'high' }
describe('units and schema', () => {
  it('converts feet and inches without drift', () => { expect(ft(1)).toBe(0.3); expect(inches(12)).toBeCloseTo(ft(1)); expect(toFeet(ft(16.5))).toBeCloseTo(16.5); expect(distanceLabel(inches(23.8))).toBe('2′ 0″') })
  it('round trips a demo and rejects invalid coefficients, dimensions, duplicate ids, and measurements', () => { expect(validateDesign(JSON.parse(JSON.stringify(demo())))).toEqual(demo()); const d = demo(); d.objects[0].absorption['125'] = 1.1; expect(() => validateDesign(d)).toThrow(); d.objects[0].absorption['125'] = 0.3; d.room.width = -1; expect(() => validateDesign(d)).toThrow(); const q = demo(); q.objects.push(q.objects[0]); expect(() => validateDesign(q)).toThrow(); const b = demo(); b.measurements.push({ id: 'm', a: { point: [0, 0, 0], objectId: 'missing' }, b: { point: [0, 0, 0] } }); expect(() => validateDesign(b)).toThrow() })
})
describe('finite plane geometry', () => {
  it('mirrors a source across a wall', () => { expect(mirror([1, 1, 2], surfaces[0])).toEqual([1, 1, -2]) })
  it('finds bounded intersections and rejects parallel, outside and endpoint-only hits', () => { expect(intersect([1, 1, 1], [1, 1, -1], surfaces[0])).toEqual([1, 1, 0]); expect(intersect([8, 1, 1], [8, 1, -1], surfaces[0])).toBeNull(); expect(intersect([1, 1, 1], [2, 1, 1], surfaces[0])).toBeNull(); expect(intersect([1, 1, 0], [1, 1, 1], surfaces[0])).toBeNull() })
  it('constructs a known first-order wall reflection', () => { const p = solvePath([1, 1, 1], [3, 1, 3], [surfaces[0]], room)!; expect(p[1][0]).toBeCloseTo(1.5); expect(p[1][2]).toBe(0); expect(distance(p[0], p[1]) + distance(p[1], p[2])).toBeCloseTo(Math.sqrt(20)) })
  it('constructs second-order paths and obeys the specular law at both contacts', () => { const p = solvePath([1, 1, 1], [3, 1.4, 4], [surfaces[0], surfaces[3]], room)!; expect(p).not.toBeNull(); expect(p).toHaveLength(4); [surfaces[0], surfaces[3]].forEach((s, i) => { const a = sub(p[i], p[i + 1]), b = sub(p[i + 2], p[i + 1]); expect(Math.abs(dot(a, s.normal)) / Math.hypot(...a)).toBeCloseTo(Math.abs(dot(b, s.normal)) / Math.hypot(...b)) }) })
  it('rejects outside sources and invalid repeated reflections', () => { expect(solvePath([-1, 1, 1], [2, 1, 3], [surfaces[0]], room)).toBeNull(); expect(solvePath([1, 1, 1], [2, 1, 3], [surfaces[0], surfaces[0]], room)).toBeNull() })
})
describe('treatment mounting and attenuation', () => {
  it('fully absorbs an oblique 20 kHz reflection with the 4-inch preset', () => {
    const panel = mountTreatmentAtPoint({ ...makeObject('panel', 'p'), size: [5, 3, inches(4)] }, 'front', [2, 1.5, 0], room)
    const d: Design = { version: 1, name: 'test', room, measurements: [], objects: [
      { ...makeObject('speaker', 's'), position: [1, 1, 1], tweeter: 0 },
      { ...makeObject('listener', 'l'), position: [4, 1, 3] }, panel,
    ] }
    const path = computePaths(d, { ...settings, listener: 'l', frequency: 20000, second: false }, { panel: true, bass: true }).find(p => p.surfaces[0] === 'Front wall')!
    expect(path).toBeDefined()
    expect(path.energy).toBe(0)
    expect(path.segmentEnergies).toEqual([1, 0])
  })

  it('snaps all six mounts and diagonal corners', () => { const base = makeObject('panel', 'p'); for (const mount of ['front', 'rear', 'left', 'right', 'ceiling', 'floor'] as const) { const o = mountObject({ ...base, mount }, room); const s = treatmentSurface(o); expect(s.center.every(Number.isFinite)).toBe(true); expect(Math.hypot(...s.normal)).toBeCloseTo(1); if (mount === 'ceiling') expect(s.normal[1]).toBeCloseTo(-1); if (mount === 'left') expect(s.normal[0]).toBeCloseTo(1) } const trap = mountObject({ ...makeObject('bass', 'b'), mount: 'front' }, room); expect(trap.rotation[1]).toBeCloseTo(Math.PI / 4) })
  it('orients a reflection absorber from the wall that owns its contact point', () => { const base = makeObject('panel', 'p'); const cases: [Parameters<typeof mountTreatmentAtPoint>[1], Vec3, Vec3][] = [['front', [2, 1, 0], [0, 0, 1]], ['rear', [2, 1, room.length], [0, 0, -1]], ['left', [0, 1, 2], [1, 0, 0]], ['right', [room.width, 1, 2], [-1, 0, 0]], ['floor', [2, 0, 2], [0, 1, 0]], ['ceiling', [2, room.height, 2], [0, -1, 0]]]; for (const [wall, point, expected] of cases) treatmentSurface(mountTreatmentAtPoint(base, wall, point, room)).normal.forEach((value, i) => expect(value).toBeCloseTo(expected[i])) })
  it('applies selected-band coefficients, segment attenuation and caps second-order paths', () => { const panel = mountTreatmentAtPoint({ ...makeObject('panel', 'p'), size: [5, 3, 0.1], curve: undefined, absorption: { '125': 0.5, '250': 0.5, '500': 0.5, '1000': 0.5, '2000': 0.5, '4000': 0.5 } }, 'front', [2, 1, 0], room); const speaker = { ...makeObject('speaker', 's'), position: [2, 1, 1] as Vec3, tweeter: 0 }; const listener = { ...makeObject('listener', 'l'), position: [2, 1, 3] as Vec3 }; const d: Design = { version: 1, name: 'test', room, measurements: [], objects: [speaker, listener, panel] }; const paths = computePaths(d, { ...settings, listener: 'l', second: false }, { panel: true, bass: true }); const reflection = paths.find(p => p.surfaces[0] === 'Front wall')!; expect(reflection.energy).toBeCloseTo(0.5); expect(reflection.segmentEnergies).toEqual([1, 0.5]); expect(paths.some(p => p.order === 1)).toBe(true); expect(computePaths(d, { ...settings, listener: 'l', enabled: false }, { panel: true, bass: true })).toEqual([]) })
  it('keeps wall paths when a mounted panel covers the contact', () => { const d: Design = { version: 1, name: 'test', room, measurements: [], objects: [{ ...makeObject('speaker', 's'), position: [1, 0.7, 1] as Vec3 }, { ...makeObject('listener', 'listener-a'), position: [1, 1, 3] as Vec3 }] }; const config = { ...settings, second: false }; const before = computePaths(d, config, { panel: true, bass: true }); expect(before.some(p => p.surfaces.includes('Front wall'))).toBe(true); d.objects.push(mountObject({ ...makeObject('panel', 'p'), mount: 'front', size: [2, 2, 0.1], offset: 0, bottom: 0 }, room)); const after = computePaths(d, config, { panel: true, bass: true }); expect(after.map(({ id, points, surfaces }) => ({ id, points, surfaces }))).toEqual(before.map(({ id, points, surfaces }) => ({ id, points, surfaces }))); expect(after.find(p => p.surfaces[0] === 'Front wall')!.energy).toBeLessThan(1) })
  it('removes a disabled absorber from the acoustic scene', () => { const d = demo(); const panel = mountObject({ ...makeObject('panel', 'p'), mount: 'front' }, d.room); d.objects.push(panel); const config = { ...settings, second: false }; const on = computePaths(d, config, { panel: true, bass: true }); panel.reflect = false; const off = computePaths(d, config, { panel: true, bass: true }); expect(off.some(p => p.surfaces.includes(panel.name))).toBe(false); expect(off.some(p => p.surfaces.includes('Front wall'))).toBe(true); expect(off.filter(p => p.surfaces.includes('Front wall')).length).toBeGreaterThanOrEqual(on.filter(p => p.surfaces.includes('Front wall')).length) })
})
