import { beforeEach, describe, expect, it } from 'vitest'
import { blankDesign, makeObject } from './model'
import { defaultLibrary, initialWorkspace, syncSofaListeners, validateWorkspace, WORKSPACE_KEY } from './workspace'
import { useStudio, workspaceData } from './store'
import { computePaths, resolveListener } from './acoustics'
import type { RaySettings } from './acoustics'
const data = new Map<string, string>()
Object.defineProperty(globalThis, 'localStorage', { value: { setItem: (k: string, v: string) => data.set(k, v), getItem: (k: string) => data.get(k) || null }, configurable: true })
beforeEach(() => { data.clear(); useStudio.setState({ design: blankDesign(), library: defaultLibrary(), milestones: [], activeMilestoneId: null, selected: null, past: [], future: [], dragStart: null }) })
const settings: RaySettings = { enabled: true, first: true, second: true, listener: 'missing-demo-id', band: '1000', surfaces: { front: true, rear: true, left: true, right: true, floor: true, ceiling: true }, maxSecond: 24, quality: 'high' }
describe('blank workspace and reusable library', () => {
  it('starts blank and defaults every treatment coefficient to 1', () => { expect(initialWorkspace().design.objects).toEqual([]); for (const o of defaultLibrary().filter(o => o.kind === 'panel' || o.kind === 'bass')) expect(Object.values(o.absorption)).toEqual([1, 1, 1, 1, 1, 1]) })
  it('uses edited dimensions for placements and applies edits to existing copies only when requested', () => { const s = useStudio.getState(); const item = { ...defaultLibrary()[0], name: 'Custom panel', size: [0.8, 1.5, 0.2] as [number, number, number] }; s.saveLibraryItem(item); const id = s.place(item.id)!; expect(useStudio.getState().design.objects.find(o => o.id === id)?.size).toEqual(item.size); s.saveLibraryItem({ ...item, size: [1, 2, 0.1] }); expect(useStudio.getState().design.objects.find(o => o.id === id)?.size).toEqual(item.size); s.saveLibraryItem({ ...item, size: [1, 2, 0.1] }, true); expect(useStudio.getState().design.objects.find(o => o.id === id)?.size).toEqual([1, 2, 0.1]); s.deleteLibraryItem(item.id); expect(useStudio.getState().design.objects).toHaveLength(1); expect(useStudio.getState().library.some(o => o.id === item.id)).toBe(false) })
  it('places speakers with edited stand defaults', () => { const s = useStudio.getState(); const stand = defaultLibrary().find(o => o.kind === 'stand')!; s.saveLibraryItem({ ...stand, size: [0.5, 0.9, 0.55] }); const id = s.place('library-speaker'); const speaker = useStudio.getState().design.objects.find(o => o.id === id)!; expect(speaker.stand.height).toBe(0.9); expect(speaker.position[1]).toBe(0.9); expect(speaker.stand.width).toBe(0.5) })
})
describe('automatic listening positions and rays', () => {
  it('creates exactly two listeners and keeps them on a translated/rotated sofa', () => { const s = useStudio.getState(); const id = s.place('library-sofa')!; expect(useStudio.getState().design.objects).toHaveLength(3); s.move(id, [2, 0, 3], [0, Math.PI / 2, 0]); const d = useStudio.getState().design, listeners = d.objects.filter(o => o.kind === 'listener'); expect(listeners).toHaveLength(2); expect(listeners.every(o => o.parentSofaId === id)).toBe(true); expect(listeners[0].position[0]).toBeCloseTo(2 - 0.85 * 0.08); expect(listeners[0].position[2]).toBeCloseTo(3 + 2 * 0.22); s.move(listeners[0].id, [9, 9, 9], [0, 0, 0]); expect(useStudio.getState().design.objects.find(o => o.id === listeners[0].id)?.position).toEqual(listeners[0].position); s.select(id); s.remove(); expect(useStudio.getState().design.objects).toHaveLength(0) })
  it('traces first and second order to a newly created listener despite stale destination IDs', () => { const s = useStudio.getState(); s.place('library-sofa'); s.place('library-speaker'); s.place('library-speaker'); const d = useStudio.getState().design; expect(resolveListener(d, settings.listener)?.kind).toBe('listener'); const paths = computePaths(d, settings, { panel: true, bass: true }); expect(paths.some(p => p.order === 1)).toBe(true); expect(paths.some(p => p.order === 2)).toBe(true); expect(new Set(paths.map(p => p.source)).size).toBe(2) })
  it('adopts legacy listeners without duplication', () => { const d = blankDesign(); d.objects = [makeObject('sofa', 'old-sofa'), makeObject('listener', 'old-a'), makeObject('listener', 'old-b')]; const next = syncSofaListeners(d); expect(next.objects).toHaveLength(3); expect(next.objects[1].parentSofaId).toBe('old-sofa') })
})
describe('permanent branching milestones', () => {
  it('restores geometry and library, preserves later saves and persists branches', () => { const s = useStudio.getState(); expect(s.saveMilestone('Blank start')).toBe(true); const start = useStudio.getState().activeMilestoneId!; s.place('library-speaker'); s.saveMilestone('Speaker placed'); const later = useStudio.getState().activeMilestoneId!; expect(s.restoreMilestone(start)).toBe(true); expect(useStudio.getState().design.objects).toHaveLength(0); s.place('library-sofa'); s.saveMilestone('Sofa branch'); const w = useStudio.getState(); expect(w.milestones).toHaveLength(3); expect(w.milestones[2].parentId).toBe(start); expect(w.milestones.some(m => m.id === later)).toBe(true); expect(validateWorkspace(JSON.parse(data.get(WORKSPACE_KEY)!))).toEqual(workspaceData(w)); expect(initialWorkspace().milestones).toHaveLength(3) })
  it('checkpoints unsaved edits before restoring an earlier save', () => { const s = useStudio.getState(); s.saveMilestone('Start'); const id = useStudio.getState().activeMilestoneId!; s.place('library-speaker'); s.restoreMilestone(id); expect(useStudio.getState().milestones).toHaveLength(2); expect(useStudio.getState().milestones[1].design.objects).toHaveLength(1) })
  it('preserves legacy autosaves as history while opening a blank room', () => { const d = blankDesign(); d.name = 'Legacy design'; d.objects.push(makeObject('speaker', 'old')); data.set('acoustic-room-visualizer-v1', JSON.stringify(d)); const w = initialWorkspace(); expect(w.design.objects).toEqual([]); expect(w.milestones[0].design.name).toBe('Legacy design'); expect(data.has('acoustic-room-visualizer-v1')).toBe(true) })
  it('rejects a save with invalid parent references', () => { const s = useStudio.getState(); s.saveMilestone('Start'); const w = structuredClone(workspaceData(useStudio.getState())); w.milestones[0].parentId = 'missing'; expect(() => validateWorkspace(w)).toThrow() })
})
