import { test, expect } from '@playwright/test';
const key = 'acoustic-room-workspace-v2';
test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => sessionStorage.setItem('acoustic-intro-seen', '1'));
  await page.goto('/');
});
test('shared inch inputs and library JSON restore with undo', async ({ page }) => {
  await page.getByRole('button', { name: 'in', exact: true }).click();
  await expect(page.getByRole('spinbutton', { name: 'Width', exact: true })).toHaveValue('192');
  await page.getByRole('spinbutton', { name: 'Width', exact: true }).fill('120');
  await page.getByRole('spinbutton', { name: 'Width', exact: true }).press('Enter');
  await page.getByRole('button', { name: 'cm', exact: true }).click();
  await expect(page.getByRole('spinbutton', { name: 'Width', exact: true })).toHaveValue('300');
  await page.getByRole('button', { name: 'Files', exact: true }).click();
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: /^Library Export/ }).click();
  const download = await downloadEvent;
  expect(download.suggestedFilename()).toBe('acoustic-room-library.json');
  const before = await page.evaluate(k => JSON.parse(localStorage.getItem(k)!), key);
  await page.getByLabel('Import library file').setInputFiles({ name: 'empty.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({format:'acoustic-room-library',version:1,library:[]})) });
  await expect.poll(() => page.evaluate(k => JSON.parse(localStorage.getItem(k)!).library.length, key)).toBe(0);
  await page.getByLabel('Import library file').setInputFiles((await download.path())!);
  expect(await page.evaluate(k => JSON.parse(localStorage.getItem(k)!).library, key)).toEqual(before.library);
  expect(await page.evaluate(k => JSON.parse(localStorage.getItem(k)!).design, key)).toEqual(before.design);
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  expect(await page.evaluate(k => JSON.parse(localStorage.getItem(k)!).library, key)).toEqual([]);
});
test('Direct and coverage buttons control paths independently of speakers', async ({ page }) => {
  await page.getByRole('button', { name: 'Files', exact: true }).click();
  await page.getByRole('button', { name: 'Open demo room', exact: true }).click();
  await page.getByRole('button', { name: 'Rays', exact: true }).click();
  const rows = page.locator('.ray-table tbody tr');
  const directRows = rows.filter({ hasText: 'Direct / incident' });
  await expect(directRows).toHaveCount(4);
  await page.getByRole('button', { name: /^Direct ━/ }).click();
  await expect(directRows).toHaveCount(0);
  await page.getByRole('button', { name: /^Direct ━/ }).click();
  await expect(directRows).toHaveCount(4);
  await page.getByRole('button', { name: 'Left speaker', exact: true }).click();
  await expect(directRows).toHaveCount(2);
  await page.getByRole('button', { name: /^Direct ━/ }).click();
  await page.getByRole('button', { name: 'Left speaker', exact: true }).click();
  await expect(directRows).toHaveCount(0);
  await page.getByRole('button', { name: /^Direct ━/ }).click();
  await expect(directRows).toHaveCount(4);
  await page.getByRole('button', { name: 'Treated rays', exact: true }).click();
  await expect(rows).toHaveCount(0);
  await page.getByRole('button', { name: 'Untreated rays', exact: true }).click();
  await expect(directRows).toHaveCount(0);
  expect(await rows.count()).toBeGreaterThan(0);
  await page.getByRole('button', { name: 'All rays', exact: true }).click();
  await expect(directRows).toHaveCount(4);
});
