import { test, expect } from '@playwright/test'
const KEY = 'acoustic-room-workspace-v2'
const tab = async (page: import('@playwright/test').Page, name: string) => page.getByRole('button', { name, exact: true }).click()
const place = async (page: import('@playwright/test').Page, name: string) => { await tab(page, 'Library'); await page.getByRole('button', { name: `Place ${name}`, exact: true }).click() }
const data = async (page: import('@playwright/test').Page) => page.evaluate(key => JSON.parse(localStorage.getItem(key) || '{}'), KEY)
const startBlankRoom = async (page: import('@playwright/test').Page) => {
  await page.goto('/')
  const create = page.getByRole('button', { name: 'Create a new room', exact: true })
  if (await create.isVisible()) await create.click()
}

test('blank start, readable themes, editable reusable panel types and default NRC', async ({ page }) => {
  await startBlankRoom(page)
  await expect(page.getByLabel('Design name')).toHaveValue('Untitled room')
  await expect(page.getByRole('button', { name: 'Axes', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByRole('button', { name: 'Dimensions', exact: true })).toHaveAttribute('aria-pressed', 'false')
  expect((await data(page)).design.objects).toHaveLength(0)
  const labelSize = await page.locator('.number-row > span').first().evaluate(e => parseFloat(getComputedStyle(e).fontSize))
  expect(labelSize).toBeGreaterThanOrEqual(14)
  await page.getByRole('button', { name: 'Toggle light and dark mode' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await tab(page, 'Library')
  await page.getByRole('button', { name: '＋ New library type' }).click()
  await page.getByRole('group', { name: 'Treatment thickness' }).getByRole('button', { name: 'Custom' }).click()
  await expect(page.locator('.library-editor .curve-title')).toContainText('NRC 0.91')
  await page.getByLabel('Library type name').fill('Cloud 4')
  await page.getByLabel('Template width', { exact: true }).fill('4')
  await page.getByLabel('Template width', { exact: true }).press('Tab')
  await page.getByLabel('Template length', { exact: true }).fill('6')
  await page.getByLabel('Template length', { exact: true }).press('Tab')
  await page.getByLabel('Custom thickness', { exact: true }).fill('4')
  await page.getByLabel('Custom thickness', { exact: true }).press('Tab')
  await page.getByRole('button', { name: 'Save type', exact: true }).click()
  await page.getByRole('button', { name: 'Edit Cloud 4', exact: true }).click()
  await page.getByLabel('NRC', { exact: true }).nth(5).fill('0.7')
  await page.getByLabel('NRC', { exact: true }).nth(5).press('Tab')
  await page.getByRole('button', { name: 'Save type', exact: true }).click()
  await page.getByRole('button', { name: 'Place Cloud 4', exact: true }).click()
  await expect(page.getByLabel('Object name')).toHaveValue('Cloud 4 1')
  let w = await data(page)
  expect(w.design.objects[0].size).toEqual([1.2, 1.7999999999999998, 0.09999999999999999])
  expect(w.design.objects[0].absorption['1000']).toBe(0.7)
  await tab(page, 'Library')
  await page.getByRole('button', { name: 'Delete type Cloud 4', exact: true }).click()
  w = await data(page)
  expect(w.library.some((q: { name: string }) => q.name === 'Cloud 4')).toBe(false)
  expect(w.design.objects).toHaveLength(1)
  await page.reload()
  expect((await data(page)).design.objects).toHaveLength(1)
})

test('save milestones survive reload and support branching to earlier progress', async ({ page }) => {
  await startBlankRoom(page)
  await page.getByRole('button', { name: 'Save / Update', exact: true }).click()
  await place(page, 'Speaker')
  await tab(page, 'Saves')
  await page.getByLabel('Milestone name').fill('Speaker setup')
  await page.getByRole('button', { name: 'Save milestone', exact: true }).click()
  await page.reload()
  await tab(page, 'Saves')
  await expect(page.getByRole('heading', { name: 'Speaker setup' })).toBeVisible()
  await page.getByRole('button', { name: 'Restore milestone 1', exact: true }).click()
  expect((await data(page)).design.objects).toHaveLength(0)
  await place(page, 'Sofa')
  await page.getByRole('button', { name: 'Save / Update', exact: true }).click()
  const w = await data(page)
  expect(w.milestones).toHaveLength(4)
  expect(w.milestones[3].parentId).toBe(w.milestones[0].id)
  expect(w.milestones[1].design.objects).toHaveLength(1)
  await tab(page, 'Saves')
  await page.waitForTimeout(250); await page.screenshot({ path: '/tmp/acoustic-history.png' })
})

test('sofa listeners, visible rays, camera views, treatment mounting and library defaults', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await startBlankRoom(page)
  await place(page, 'Sofa')
  let w = await data(page)
  expect(w.design.objects.filter((o: { kind: string }) => o.kind === 'listener')).toHaveLength(2)
  await place(page, 'Speaker'); await place(page, 'Speaker')
  await tab(page, 'Rays')
  await expect(page.getByRole('table', { name: 'Ray paths' }).locator('tbody tr').first()).toBeVisible()
  await page.getByRole('group', { name: 'Listeners' }).getByRole('button', { name: 'Listener A' }).click()
  await page.getByLabel('Frequency slider').fill('0.265')
  expect(await page.getByRole('table', { name: 'Ray paths' }).locator('tbody tr').count()).toBeGreaterThan(10)
  await page.getByRole('table', { name: 'Ray paths' }).getByRole('button').first().click()
  await expect(page.getByText('Energy retained', { exact: true })).toBeVisible()
  for (const view of ['Front', 'Rear', 'Left', 'Right', 'Top', 'Side', 'Perspective']) { await page.getByLabel('Camera view', { exact: true }).selectOption(view); await page.waitForTimeout(90) }
  await place(page, 'Absorption panel')
  for (const mount of ['front', 'rear', 'left', 'right', 'ceiling', 'floor', 'free']) await page.getByLabel('Mounting surface').selectOption(mount)
  await page.getByLabel('Mounting surface').selectOption('ceiling')
  w = await data(page)
  expect(w.design.objects.find((o: { kind: string }) => o.kind === 'panel').absorption['1000']).toBe(1)
  await tab(page, 'Rays')
  await expect(page.getByRole('table', { name: 'Ray paths' }).locator('tbody tr').first()).toBeVisible()
  await page.locator('.panel-scroll').evaluate(e => e.scrollTop = 0)
  await page.waitForTimeout(250); await page.screenshot({ path: '/tmp/acoustic-rays-dark.png' })
  await page.getByRole('button', { name: 'Toggle light and dark mode' }).click()
  await page.waitForTimeout(250); await page.screenshot({ path: '/tmp/acoustic-rays-light.png' })
  await page.reload()
  await tab(page, 'Rays')
  await expect(page.getByRole('table', { name: 'Ray paths' }).locator('tbody tr').first()).toBeVisible()
  expect(errors).toEqual([])
})

test('versioned design/history export, invalid import and responsive layout', async ({ page }) => {
  await startBlankRoom(page)
  await place(page, 'Sofa')
  await page.getByRole('button', { name: 'Save / Update', exact: true }).click()
  await tab(page, 'Files')
  const event = page.waitForEvent('download')
  await page.getByRole('button', { name: /^Export workspace history/ }).click()
  expect((await event).suggestedFilename()).toBe('acoustic-room-history.json')
  await page.getByLabel('Import design file').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"version":9}') })
  await expect(page.locator('.notification')).toContainText('Invalid design')
  const original = await data(page)
  const imported = structuredClone(original); imported.design.name = 'Imported room'
  await page.getByLabel('Import design file').setInputFiles({ name: 'history.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(imported)) })
  await expect(page.getByLabel('Design name')).toHaveValue('Imported room')
  expect((await data(page)).milestones.length).toBeGreaterThan(original.milestones.length)
  await page.getByTitle('Collapse editing panel').click()
  await page.getByTitle('Expand editing panel').click()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator('canvas')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)).toBe(false)
  await page.waitForTimeout(250); await page.screenshot({ path: '/tmp/acoustic-mobile-v2.png', fullPage: true })
})

test('gizmo movement keeps listeners seated and custom measurements work', async ({ page }) => {
  await startBlankRoom(page)
  await place(page, 'Sofa')
  const before = await data(page), sofa = before.design.objects.find((o: { kind: string }) => o.kind === 'sofa')
  const rect = (await page.locator('canvas').boundingBox())!
  const { PerspectiveCamera, Vector3 } = await import('three')
  const r = before.design.room, span = r.length * 1.65
  const camera = new PerspectiveCamera(42, rect.width / rect.height, 0.05, 200)
  camera.position.set(r.width / 2 + span * 0.8, r.height / 2 + span * 0.65, r.length / 2 + span)
  camera.lookAt(r.width / 2, r.height / 2, r.length / 2); camera.updateMatrixWorld()
  const project = (x: number, y: number, z: number) => { const p = new Vector3(x, y, z).project(camera); return { x: rect.x + (p.x + 1) * rect.width / 2, y: rect.y + (1 - p.y) * rect.height / 2 } }
  const handle = project(sofa.position[0] + 0.6, sofa.position[1], sofa.position[2])
  await page.mouse.move(handle.x, handle.y); await page.mouse.down(); await page.mouse.move(handle.x + 65, handle.y + 20, { steps: 12 }); await page.mouse.up()
  const moved = await data(page), afterSofa = moved.design.objects.find((o: { kind: string }) => o.kind === 'sofa')
  expect(afterSofa.position).not.toEqual(sofa.position)
  const listener = moved.design.objects.find((o: { kind: string }) => o.kind === 'listener')
  expect(listener.position[0]).toBeCloseTo(afterSofa.position[0] - sofa.size[0] * 0.22)
  await tab(page, 'Measure')
  await page.getByRole('button', { name: '＋ Measure two points' }).click()
  const a = project(0.2, 1.8, 0), b = project(3.5, 1.8, 0)
  await page.mouse.click(a.x, a.y); await page.mouse.click(b.x, b.y)
  await expect(page.getByText('Measurement 1', { exact: true })).toBeVisible()
})

test('reflection treatment optimizer uses the selected absorber and per-surface orientation', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Create a new room', exact: true }).click()
  await place(page, 'Sofa')
  await place(page, 'Speaker')
  await place(page, 'Speaker')
  await tab(page, 'Rays')
  await expect(page.getByRole('button', { name: '✦ Optimize panels', exact: true })).toBeVisible()
  for (const surface of ['Front wall', 'Rear wall', 'Left wall', 'Right wall', 'Floor', 'Ceiling']) {
    await expect(page.getByLabel(`${surface} panel`, { exact: true })).toHaveCount(0)
    for (const dimension of ['length', 'width', 'thickness'])
      await expect(page.getByLabel(`${surface} panel ${dimension}`, { exact: true })).toBeEnabled()
  }
  await page.getByRole('button', { name: 'Rear wall', exact: true }).click()
  await expect(page.getByRole('group', { name: 'Rear wall panel orientation', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Rear wall', exact: true }).click()
  await expect(page.getByRole('group', { name: 'Rear wall panel orientation', exact: true })).toBeVisible()
  const rayTable = page.getByRole('table', { name: 'Ray paths' })
  await expect(rayTable.getByRole('columnheader')).toHaveText(['Source', 'Destination', 'Order', 'Surfaces', 'Path length', 'Travel time', 'Energy retained', 'Visual loss'])
  await rayTable.getByRole('button').first().click()
  await expect(rayTable.locator('tbody tr').first()).toHaveAttribute('data-selected', 'true')
  await expect(rayTable.getByRole('button').first()).toHaveAttribute('aria-pressed', 'true')
  expect(await page.getByRole('region', { name: 'Ray inspector table', exact: true }).evaluate(el => el.getBoundingClientRect().height)).toBeLessThanOrEqual(282)
  const routes = await page.getByRole('table', { name: 'Ray paths' }).locator('tbody tr').evaluateAll(rows => rows.map(row => ({ value: row.getAttribute('data-ray-id'), text: Array.from(row.querySelectorAll('td')).slice(0, 5).map(cell => cell.textContent).join('|') })))
  const frontOrientation = page.getByRole('group', { name: 'Front wall panel orientation', exact: true })
  await frontOrientation.getByRole('button', { name: 'Horizontal', exact: true }).click()
  await expect(frontOrientation.getByRole('button', { name: 'Horizontal', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '＋ Add absorbers', exact: true }).click()
  const before = await data(page)
  const generatedBefore = before.design.objects.filter((o: { kind: string }) => o.kind === 'panel').length
  expect(generatedBefore).toBeGreaterThan(1)
  await page.getByRole('button', { name: '✦ Optimize panels', exact: true }).click()
  const after = await data(page)
  const panels = after.design.objects.filter((o: { kind: string }) => o.kind === 'panel')
  expect(panels.length).toBeLessThan(generatedBefore)
  expect(panels.every((o: { name: string }) => o.name.startsWith('Optimized '))).toBe(true)
  expect(panels.some((o: { name: string; size: number[] }) => o.name.startsWith('Optimized horizontal') && o.size[0] > o.size[1])).toBe(true)
  const readRoutes = () => page.getByRole('table', { name: 'Ray paths' }).locator('tbody tr').evaluateAll(rows => rows.map(row => ({ value: row.getAttribute('data-ray-id'), text: Array.from(row.querySelectorAll('td')).slice(0, 5).map(cell => cell.textContent).join('|') })))
  expect(await readRoutes()).toEqual(routes)
  await page.getByRole('button', { name: 'All off', exact: true }).click()
  expect(await readRoutes()).toEqual(routes)
  await page.getByRole('button', { name: 'All on', exact: true }).click()
  expect(await readRoutes()).toEqual(routes)
  await frontOrientation.getByRole('button', { name: 'Vertical', exact: true }).click()
  await page.getByRole('button', { name: '✦ Optimize panels', exact: true }).click()
  expect((await data(page)).design.objects.filter((o: { kind: string }) => o.kind === 'panel').every((o: { size: number[] }) => o.size[1] > o.size[0])).toBe(true)
  expect(await readRoutes()).toEqual(routes)
})

test('surface panel dropdowns choose library sizes independently', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Create a new room', exact: true }).click()
  await place(page, 'Sofa')
  await place(page, 'Speaker')
  const saved = await data(page)
  const original = saved.library.find((item: { kind: string }) => item.kind === 'panel')
  const alternate = { ...original, id: 'test-alternate', name: 'Small absorber', size: [0.4, 0.8, 0.0508] }
  saved.library.push(alternate)
  await page.evaluate(({ key, saved }) => localStorage.setItem(key, JSON.stringify(saved)), { key: KEY, saved })
  await page.reload()
  await tab(page, 'Rays')
  await page.getByLabel('Front wall panel thickness', { exact: true }).selectOption('0.0508')
  await expect(page.getByLabel('Front wall panel', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Front wall panel length', { exact: true })).toHaveValue('0.8')
  await expect(page.getByLabel('Front wall panel width', { exact: true })).toHaveValue('0.4')
  await expect(page.getByLabel('Rear wall panel thickness', { exact: true })).toHaveValue(String(original.size[2]))
  await page.getByRole('button', { name: '✦ Optimize panels', exact: true }).click()
  const panels = (await data(page)).design.objects.filter((o: { kind: string }) => o.kind === 'panel')
  const front = panels.filter((o: { mount: string }) => o.mount === 'front')
  expect(front.length).toBeGreaterThan(0)
  for (const panel of front) {
    expect(panel.templateId).toBe(alternate.id)
    expect(panel.size).toEqual(alternate.size)
    expect(panel.absorption).toEqual(alternate.absorption)
  }
  expect(panels.some((o: { mount: string; templateId: string }) => o.mount !== 'front' && o.templateId === original.id)).toBe(true)
})
