import { test, expect } from '@playwright/test'
const KEY = 'acoustic-room-workspace-v2'
const tab = async (page: import('@playwright/test').Page, name: string) => page.getByRole('button', { name, exact: true }).click()
const place = async (page: import('@playwright/test').Page, name: string) => { await tab(page, 'Library'); await page.getByRole('button', { name: `Place ${name}`, exact: true }).click() }
const data = async (page: import('@playwright/test').Page) => page.evaluate(key => JSON.parse(localStorage.getItem(key) || '{}'), KEY)

test('blank start, readable themes, editable reusable panel types and default NRC', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Untitled room' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Axes', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByRole('button', { name: 'Dimensions', exact: true })).toHaveAttribute('aria-pressed', 'false')
  expect((await data(page)).design.objects).toHaveLength(0)
  const labelSize = await page.locator('.number-row > span').first().evaluate(e => parseFloat(getComputedStyle(e).fontSize))
  expect(labelSize).toBeGreaterThanOrEqual(14)
  await page.getByRole('button', { name: 'Toggle light and dark mode' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await tab(page, 'Library')
  await page.getByRole('button', { name: '＋ New library type' }).click()
  await expect(page.getByLabel('NRC', { exact: true })).toHaveValue('1')
  await page.getByLabel('Library type name').fill('Cloud 4')
  await page.getByLabel('Template width', { exact: true }).fill('4')
  await page.getByLabel('Template width', { exact: true }).press('Tab')
  await page.getByLabel('Template length', { exact: true }).fill('6')
  await page.getByLabel('Template length', { exact: true }).press('Tab')
  await page.getByLabel('Template thickness', { exact: true }).fill('4')
  await page.getByLabel('Template thickness', { exact: true }).press('Tab')
  await page.getByRole('button', { name: 'Save type', exact: true }).click()
  await page.getByRole('button', { name: 'Edit Cloud 4', exact: true }).click()
  await page.getByLabel('NRC', { exact: true }).fill('0.7')
  await page.getByLabel('NRC', { exact: true }).press('Tab')
  await page.getByRole('button', { name: 'Save type', exact: true }).click()
  await page.getByRole('button', { name: 'Place Cloud 4', exact: true }).click()
  await expect(page.getByLabel('Object name')).toHaveValue('Cloud 4 1')
  let w = await data(page)
  expect(w.design.objects[0].size).toEqual([1.2192, 1.8288000000000002, 0.1016])
  expect(w.design.objects[0].absorption['1000']).toBe(0.7)
  await tab(page, 'Library')
  await page.getByRole('button', { name: 'Delete type Cloud 4', exact: true }).click()
  w = await data(page)
  expect(w.library.some((q: { name: string }) => q.name === 'Cloud 4')).toBe(false)
  expect(w.design.objects).toHaveLength(1)
  await page.reload()
  expect((await data(page)).design.objects).toHaveLength(1)
})

test('save milestones survive reload and support branching to earlier progress', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Save / Update', exact: true }).click()
  await place(page, 'Speaker')
  await tab(page, 'Saves')
  await page.getByLabel('Milestone name').fill('Speaker setup')
  await page.getByRole('button', { name: 'Save / Update milestone', exact: true }).click()
  await page.reload()
  await tab(page, 'Saves')
  await expect(page.getByRole('heading', { name: 'Speaker setup' })).toBeVisible()
  await page.getByRole('button', { name: 'Restore milestone 1', exact: true }).click()
  expect((await data(page)).design.objects).toHaveLength(0)
  await place(page, 'Sofa')
  await page.getByRole('button', { name: 'Save / Update', exact: true }).click()
  const w = await data(page)
  expect(w.milestones).toHaveLength(3)
  expect(w.milestones[2].parentId).toBe(w.milestones[0].id)
  expect(w.milestones[1].design.objects).toHaveLength(1)
  await tab(page, 'Saves')
  await page.waitForTimeout(250); await page.screenshot({ path: '/tmp/acoustic-history.png' })
})

test('sofa listeners, visible rays, camera views, treatment mounting and library defaults', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await place(page, 'Sofa')
  let w = await data(page)
  expect(w.design.objects.filter((o: { kind: string }) => o.kind === 'listener')).toHaveLength(2)
  await place(page, 'Speaker'); await place(page, 'Speaker')
  await expect(page.getByTestId('ray-count')).not.toHaveText(/^0 valid/)
  await tab(page, 'Rays')
  await page.getByLabel('Second order · two reflections').check()
  await page.getByLabel('Destination listener').selectOption({ label: 'Listener B' })
  await page.getByLabel('Frequency band').selectOption('125')
  expect(await page.getByLabel('Select ray').locator('option').count()).toBeGreaterThan(10)
  await page.getByLabel('Select ray').selectOption({ index: 1 })
  await expect(page.getByText('Energy retained', { exact: true })).toBeVisible()
  for (const view of ['Front', 'Rear', 'Left', 'Right', 'Top', 'Side', 'Perspective']) { await page.getByLabel('Camera view').selectOption(view); await page.waitForTimeout(90) }
  await page.getByRole('button', { name: 'See-through', exact: true }).click()
  await page.getByRole('button', { name: 'See-through', exact: true }).click()
  await place(page, 'Absorption panel')
  for (const mount of ['front', 'rear', 'left', 'right', 'ceiling', 'floor', 'free']) await page.getByLabel('Mounting surface').selectOption(mount)
  await page.getByLabel('Mounting surface').selectOption('ceiling')
  w = await data(page)
  expect(w.design.objects.find((o: { kind: string }) => o.kind === 'panel').absorption['1000']).toBe(1)
  await tab(page, 'Rays')
  await expect(page.getByTestId('ray-count')).not.toHaveText(/^0 valid/)
  await page.locator('.panel-scroll').evaluate(e => e.scrollTop = 0)
  await page.waitForTimeout(250); await page.screenshot({ path: '/tmp/acoustic-rays-dark.png' })
  await page.getByRole('button', { name: 'Toggle light and dark mode' }).click()
  await page.waitForTimeout(250); await page.screenshot({ path: '/tmp/acoustic-rays-light.png' })
  await page.reload()
  await expect(page.getByTestId('ray-count')).not.toHaveText(/^0 valid/)
  expect(errors).toEqual([])
})

test('versioned design/history export, invalid import and responsive layout', async ({ page }) => {
  await page.goto('/')
  await place(page, 'Sofa')
  await page.getByRole('button', { name: 'Save / Update', exact: true }).click()
  await tab(page, 'Files')
  const event = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export workspace history', exact: true }).click()
  expect((await event).suggestedFilename()).toBe('acoustic-room-history.json')
  await page.getByLabel('Import design file').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"version":9}') })
  await expect(page.locator('.notification')).toContainText('Invalid design')
  const original = await data(page)
  const imported = structuredClone(original); imported.design.name = 'Imported room'
  await page.getByLabel('Import design file').setInputFiles({ name: 'history.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(imported)) })
  await expect(page.getByRole('heading', { name: 'Imported room' })).toBeVisible()
  expect((await data(page)).milestones.length).toBeGreaterThan(original.milestones.length)
  await page.getByTitle('Collapse editing panel').click()
  await page.getByTitle('Expand tool panel').click()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator('canvas')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)).toBe(false)
  await page.waitForTimeout(250); await page.screenshot({ path: '/tmp/acoustic-mobile-v2.png', fullPage: true })
})

test('gizmo movement keeps listeners seated and custom measurements work', async ({ page }) => {
  await page.goto('/')
  await place(page, 'Sofa')
  const before = await data(page), sofa = before.design.objects.find((o: { kind: string }) => o.kind === 'sofa')
  const rect = (await page.locator('canvas').boundingBox())!
  const { PerspectiveCamera, Vector3 } = await import('three')
  const r = before.design.room, span = r.length * 1.65
  const camera = new PerspectiveCamera(42, rect.width / rect.height, 0.05, 200)
  camera.position.set(r.width / 2 + span * 0.8, r.height / 2 + span * 0.65, r.length / 2 + span)
  camera.lookAt(r.width / 2, r.height / 2, r.length / 2); camera.updateMatrixWorld()
  const project = (x: number, y: number, z: number) => { const p = new Vector3(x, y, z).project(camera); return { x: rect.x + (p.x + 1) * rect.width / 2, y: rect.y + (1 - p.y) * rect.height / 2 } }
  const handle = project(sofa.position[0] + 0.6, sofa.position[1], sofa.position[2])
  await page.mouse.move(handle.x, handle.y); await page.mouse.down(); await page.mouse.move(handle.x + 65, handle.y + 20, { steps: 12 }); await page.mouse.up()
  const moved = await data(page), afterSofa = moved.design.objects.find((o: { kind: string }) => o.kind === 'sofa')
  expect(afterSofa.position).not.toEqual(sofa.position)
  const listener = moved.design.objects.find((o: { kind: string }) => o.kind === 'listener')
  expect(listener.position[0]).toBeCloseTo(afterSofa.position[0] - sofa.size[0] * 0.22)
  await tab(page, 'Measure')
  await page.getByRole('button', { name: '＋ Measure two points' }).click()
  const a = project(0.2, 1.8, 0), b = project(3.5, 1.8, 0)
  await page.mouse.click(a.x, a.y); await page.mouse.click(b.x, b.y)
  await expect(page.getByText('Measurement 1', { exact: true })).toBeVisible()
})
