import { useRef } from 'react'
import { blankDesign, validateDesign } from '../domain/model'
import { validateLibrary, validateWorkspace } from '../domain/workspace'
import { useStudio, workspaceData } from '../domain/store'
import { Section } from './Controls'
function downloadJson(value: unknown, filename: string) { const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = filename; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) }
export default function FilesPanel({ unit, onUnit, onMessage, onHistory }: { unit: 'ft' | 'm'; onUnit: (u: 'ft' | 'm') => void; onMessage: (m: string) => void; onHistory: () => void }) {
  const input = useRef<HTMLInputElement>(null)
  return <><Section title="Design & backups"><label className="text-field">Display units<select aria-label="Display units" value={unit} onChange={e => onUnit(e.target.value as 'ft' | 'm')}><option value="ft">Feet / inches</option><option value="m">Meters</option></select></label><div className="file-actions">
    <button onClick={() => { const s = useStudio.getState(); if (!s.saveMilestone('Before new room')) { onMessage('Unable to save your current progress. Export a backup before starting a new room.'); return } s.commit(blankDesign()); s.select(null); onMessage('Blank room created. Your previous room is in Save history.') }}>＋ New blank room</button>
    <button onClick={onHistory}>View save history</button>
    <button onClick={() => { const s = useStudio.getState(); downloadJson({ ...s.design, library: s.library }, 'acoustic-room-design.json'); onMessage('Design and reusable library exported.') }}>Export design JSON</button>
    <button onClick={() => { downloadJson(workspaceData(useStudio.getState()), 'acoustic-room-history.json'); onMessage('Full workspace exported, including every milestone and branch.') }}>Export workspace history</button>
    <button onClick={() => input.current?.click()}>Import JSON</button>
  </div><input ref={input} type="file" className="hidden-input" aria-label="Import design file" accept=".json,application/json" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; try { if (file.size > 20_000_000) throw new Error('File is too large. Maximum size is 20 MB.'); const data = JSON.parse(await file.text()); const parsed = data.version === 2 ? validateWorkspace(data) : validateDesign(data); const library = data.version === 1 && data.library ? validateLibrary(data.library) : null; const s = useStudio.getState(); if (!s.saveMilestone('Before import')) throw new Error('Unable to checkpoint current progress. Export a backup before importing.'); if (parsed.version === 2) s.importWorkspace(parsed); else { if (library) s.importWorkspace({ version: 2, design: parsed, library, milestones: [], activeMilestoneId: null }); else s.commit(parsed) } s.select(null); onMessage('Import complete. Previous progress and saves remain in your history.') } catch (error) { onMessage(error instanceof SyntaxError ? 'This file is not valid JSON. Your design is unchanged.' : error instanceof Error ? error.message : 'Import failed. Your design is unchanged.') } e.target.value = '' }} /><p className="hint">Your working design autosaves locally. Save / Update creates a permanent milestone. A full workspace export includes all saves; a design export includes the current room and library.</p></Section><Section title="About reflection output"><p className="hint">Approximate specular geometric visualization, not an acoustical measurement or prediction. Absorption values reduce visual energy. Room modes, wave interference, scattering, diffraction and calibrated SPL are not modeled.</p></Section></>
}
