import {useState} from 'react'
import {useStudio} from '../domain/store'
import {Section} from './Controls'
import Icon from './Icon'
export default function HistoryPanel({onMessage}:{onMessage:(m:string)=>void}) {
 const {milestones,activeMilestoneId,saveMilestone,restoreMilestone,deleteMilestone,deleteAllMilestones}=useStudio()
 const [name,setName]=useState(''),[pending,setPending]=useState<string|null>(null),[confirmation,setConfirmation]=useState('')
 const ask=(id:string)=>{setPending(id);setConfirmation('')}
 return <><Section title="Save a milestone"><label className="text-field">Name your progress<input aria-label="Milestone name" placeholder="e.g. First reflection treatment" value={name} maxLength={100} onChange={e=>setName(e.target.value)}/></label><button className="primary history-save" onClick={()=>{const ok=saveMilestone(name);onMessage(ok?'Milestone saved.':'Could not save. Export a backup from Files.');if(ok)setName('')}}><Icon name="save"/>Save milestone</button><p className="hint">Capture the room and library together. Restore any save without losing later milestones.</p></Section>
 <Section title="Timeline" extra={<span className="badge">{milestones.length} saves</span>}><div className="history-tools"><span>Newest first</span><button className="danger" disabled={!milestones.length} onClick={()=>ask('all')}><Icon name="delete"/>Delete all</button></div>{!milestones.length&&<p className="hint">Your first milestone will appear here.</p>}<ol className="save-timeline">{milestones.map((m,index)=>({m,index})).reverse().map(({m,index})=><li key={m.id} className={m.id===activeMilestoneId?'current':''}><header><span>#{index+1}</span>{m.id===activeMilestoneId&&<span className="badge">Current base</span>}</header><h3>{m.label}</h3><time dateTime={m.createdAt}>{new Date(m.createdAt).toLocaleString()}</time><p>{m.design.objects.length} objects · {m.library.length} library types</p><small>{m.parentId ? `From save #${milestones.findIndex(q=>q.id===m.parentId)+1}`:'Starting point'}</small><footer><button onClick={()=>onMessage(restoreMilestone(m.id)?`Restored “${m.label}”.`:'Unable to checkpoint current work. Export a backup first.')} aria-label={`Restore milestone ${index+1}`}><Icon name="Saves"/>Restore</button><button title="Delete this save" aria-label={`Delete ${m.label}`} onClick={()=>ask(m.id)}><Icon name="delete"/></button></footer></li>)}</ol></Section>
 {pending&&<div className="modal-backdrop"><div className="guide-modal confirm-modal" role="dialog" aria-modal="true" aria-label="Delete saves confirmation"><h2>{pending==='all'?'Delete all saved milestones?':'Delete this milestone?'}</h2><p>Your current room stays intact. This removes {pending==='all'?'all saved history':'this save'} permanently. Type <b>delete</b> to confirm.</p><input autoFocus aria-label="Delete confirmation" placeholder="Type delete" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/><button className="danger" disabled={confirmation!=='delete'} onClick={()=>{const ok=pending==='all'?deleteAllMilestones():deleteMilestone(pending);onMessage(ok?'Saved history deleted.':'Could not delete saved history.');if(ok)setPending(null)}}>Delete permanently</button><button onClick={()=>setPending(null)}>Cancel</button></div></div>}</>
}
