import { useEffect, useState } from 'react'
import { bands, distanceLabel, ft, inches, makeObject, toFeet, unityAbsorption } from '../domain/model'
import type { Vec3 } from '../domain/model'
import type { LibraryItem } from '../domain/workspace'
import { validateLibrary } from '../domain/workspace'
import { useStudio } from '../domain/store'
import { NumberField, Section } from './Controls'
export default function LibraryPanel({ unit, onPlace, onMessage }: { unit: 'ft' | 'm'; onPlace: (id: string) => void; onMessage: (message: string) => void }) {
  const library = useStudio(s => s.library), saveItem = useStudio(s => s.saveLibraryItem), deleteItem = useStudio(s => s.deleteLibraryItem)
  const [draft, setDraft] = useState<LibraryItem | null>(null), [creating, setCreating] = useState(false), [apply, setApply] = useState(false)
  const draftId = draft?.id
  useEffect(() => { if (draftId) document.querySelector('.library-editor')?.scrollIntoView({ block: 'start' }) }, [draftId])
  const edit = (item: LibraryItem) => { setDraft(structuredClone(item)); setCreating(false); setApply(false) }
  const start = (kind: LibraryItem['kind'] = 'panel') => { setDraft({ ...makeObject(kind), kind, ...(kind === 'speaker' ? { standTemplateId: library.find(q => q.kind === 'stand')?.id } : {}) }); setCreating(true); setApply(false) }
  const update = (p: Partial<LibraryItem>) => setDraft(d => d ? { ...d, ...p } : null)
  const dim = (label: string, i: number) => draft && <NumberField label={label} value={unit === 'ft' ? toFeet(draft.size[i]) : draft.size[i]} min={unit === 'ft' ? 0.05 : 0.015} max={unit === 'ft' ? 30 : 9} suffix={unit} onChange={n => { const size = [...draft.size] as Vec3; size[i] = unit === 'ft' ? ft(n) : n; update({ size }) }} />
  const nrc = draft ? (draft.absorption['250'] + draft.absorption['500'] + draft.absorption['1000'] + draft.absorption['2000']) / 4 : 1
  const persist = () => { if (!draft) return; try { if (creating && library.length >= 150) throw new Error('The library supports up to 150 types. Delete an unused type first.'); if (!draft.name.trim()) throw new Error('Give this library type a name.'); validateLibrary([draft]); saveItem({ ...draft, name: draft.name.trim() }, apply); setDraft(null); onMessage(apply ? 'Library type and its placed copies updated.' : 'Library type saved. New placements will use these settings.') } catch (e) { onMessage(e instanceof Error ? e.message : 'Unable to save this library type.') } }
  return <>
    <Section title="Object & treatment library"><p className="hint">Set dimensions once, then place as many copies as you need. Edit or delete any type at any time.</p><button className="wide-button" onClick={() => start()}>＋ New library type</button></Section>
    {draft && <Section title={creating ? 'Add a library type' : 'Edit library type'} extra={<button aria-label="Close library editor" onClick={() => setDraft(null)}>×</button>}><div className="library-editor">
      <label className="text-field">Type<select aria-label="Library type" value={draft.kind} disabled={!creating} onChange={e => { const kind = e.target.value as LibraryItem['kind']; setDraft({ ...makeObject(kind, draft.id), kind, ...(kind === 'speaker' ? { standTemplateId: library.find(q => q.kind === 'stand')?.id } : {}) }) }}><option value="panel">Absorption panel</option><option value="bass">Corner bass trap</option><option value="speaker">Speaker</option><option value="stand">Speaker stand</option><option value="sofa">Sofa</option></select></label>
      <label className="text-field">Type name<input aria-label="Library type name" value={draft.name} maxLength={100} onChange={e => update({ name: e.target.value })} /></label>
      {dim('Template width', 0)}{dim(draft.kind === 'panel' || draft.kind === 'bass' ? 'Template length' : 'Template height', 1)}
      {draft.kind === 'panel' || draft.kind === 'bass' ? <><NumberField label="Template thickness" value={draft.size[2] / 0.0254} min={0.25} max={24} suffix="in" onChange={n => update({ size: [draft.size[0], draft.size[1], inches(n)] })} /><NumberField label="NRC" value={nrc} min={0} max={1} step={0.01} onChange={n => update({ absorption: Object.fromEntries(bands.map(b => [b, n])) as LibraryItem['absorption'] })} /><p className="hint">Starts at 1.00. Entering NRC sets every band to that value. Expand below if you have separate band data.</p><details><summary>Per-frequency absorption data</summary>{bands.map(b => <NumberField key={b} label={`Library ${b} Hz`} value={draft.absorption[b]} min={0} max={1} step={0.01} onChange={n => update({ absorption: { ...draft.absorption, [b]: n } })} />)}<button onClick={() => update({ absorption: unityAbsorption() })}>Reset to 1.00</button></details><p className="hint">NRC-style average is informational. Coefficients control visual ray attenuation only.</p></> : dim('Template depth', 2)}
      {draft.kind === 'speaker' && <><NumberField label="Template tweeter height" value={unit === 'ft' ? toFeet(draft.tweeter) : draft.tweeter} min={0} max={unit === 'ft' ? toFeet(draft.size[1]) : draft.size[1]} suffix={unit} onChange={n => update({ tweeter: unit === 'ft' ? ft(n) : n })} /><label className="text-field">Stand type<select aria-label="Speaker stand type" value={draft.standTemplateId || ''} onChange={e => update({ standTemplateId: e.target.value || undefined })}><option value="">Custom stand dimensions</option>{library.filter(q => q.kind === 'stand').map(q => <option key={q.id} value={q.id}>{q.name}</option>)}</select></label>{!draft.standTemplateId && <>{(['height', 'width', 'depth'] as const).map(k => <NumberField key={k} label={`Template stand ${k}`} value={unit === 'ft' ? toFeet(draft.stand[k] || 0.34) : draft.stand[k] || 0.34} min={0.01} max={10} suffix={unit} onChange={n => update({ stand: { ...draft.stand, [k]: unit === 'ft' ? ft(n) : n } })} />)}</>}</>}
      {draft.kind === 'stand' && <NumberField label="Stand post width" value={(draft.stand.postWidth || 0.065) / 0.0254} min={0.25} max={12} suffix="in" onChange={n => update({ stand: { ...draft.stand, postWidth: inches(n) } })} />}
      {draft.kind === 'sofa' && <p className="model-notice">Two listeners are included automatically. They stay seated as you move, rotate or resize the sofa.</p>}
      <label className="color-row">Color<input type="color" aria-label="Library color" value={draft.color} onChange={e => update({ color: e.target.value })} /></label>
      {!creating && <label className="toggle-row"><span>Also update placed copies</span><input type="checkbox" checked={apply} onChange={e => setApply(e.target.checked)} /></label>}
      <div className="button-pair"><button className="primary" onClick={persist}>Save type</button><button onClick={() => setDraft(null)}>Cancel</button></div>
    </div></Section>}
    {([['panel', 'Treatment Library'], ['bass', 'Corner bass traps'], ['speaker', 'Speakers'], ['stand', 'Speaker stands'], ['sofa', 'Sofas']] as const).map(([kind, title]) => <Section key={kind} title={title} extra={<button aria-label={`Add ${kind} type`} onClick={() => start(kind)}>＋</button>}>
      {library.filter(q => q.kind === kind).length === 0 && <p className="hint">No types yet. Use ＋ to create one.</p>}
      <div className="template-list">{library.filter(q => q.kind === kind).map(item => <article className="template-card" key={item.id} draggable onDragStart={e => e.dataTransfer.setData('application/acoustic-template', item.id)}>
        <div className="template-heading"><span className={`library-art ${kind === 'bass' ? 'bass-art' : ''}`} style={{ backgroundColor: item.color }} /><div><h3>{item.name}</h3><p>{item.size.map(n => distanceLabel(n, unit)).join(' × ')}</p>{(kind === 'panel' || kind === 'bass') && <p>NRC {((item.absorption['250'] + item.absorption['500'] + item.absorption['1000'] + item.absorption['2000']) / 4).toFixed(2)}</p>}{kind === 'sofa' && <p>Includes Listener A + B</p>}</div></div>
        <div className="template-actions"><button className="primary" aria-label={`Place ${item.name}`} onClick={() => onPlace(item.id)}>＋ Place</button><button aria-label={`Edit ${item.name}`} onClick={() => edit(item)}>Edit</button><button aria-label={`Delete type ${item.name}`} onClick={() => { deleteItem(item.id); if (draft?.id === item.id) setDraft(null); onMessage('Type deleted from the library. Placed objects are kept; Undo restores the type.') }}>Delete</button></div>
      </article>)}</div>
    </Section>)}
  </>
}
