import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
await page.goto('http://127.0.0.1:5173');
await page.getByRole('button',{name:'Create a new room',exact:true}).click();
await page.getByRole('button',{name:'Files',exact:true}).click();
await page.getByRole('button',{name:'Open demo room',exact:true}).click();
await expect(page.getByLabel('Design name')).toHaveValue('The listening room');
await expect(page.locator('.viewport-guidance')).toHaveCount(0);
await page.getByRole('button',{name:'Design',exact:true}).click();
await page.getByLabel('Find placed objects').fill('Left speaker');
await expect(page.locator('.object-grid .object-row')).toHaveCount(1);
await page.getByRole('button',{name:'Select Left speaker',exact:true}).click();
await expect(page.getByRole('button',{name:'Select Left speaker',exact:true})).toHaveAttribute('aria-pressed','true');
await page.getByRole('button',{name:'Show Left speaker',exact:true}).click();
await expect(page.getByRole('button',{name:'Show Left speaker',exact:true})).toHaveAttribute('aria-pressed','false');
await page.getByLabel('Find placed objects').fill('');
await page.screenshot({path:'/tmp/acoustic-object-cards.png'});
await page.getByRole('button',{name:'Library',exact:true}).click();
await expect(page.getByRole('button',{name:'Place Absorption panel',exact:true})).toBeVisible();
await page.screenshot({path:'/tmp/acoustic-library-cards.png'});
await page.getByRole('button',{name:'Edit Absorption panel',exact:true}).click();
await expect(page.getByLabel('Library type name')).toBeVisible();
await browser.close();console.log('PASS: overlay removed, object search/selection/visibility, library actions and editor.');
